// Canonical catalog of every data source FloodDash uses — polled pipelines,
// map-only remote-sensing layers (JAXA / NASA GIBS / RainViewer), and the
// compiled exports we serve from SQLite. Exposed at GET /api/sources for
// researchers and integrators who want to reuse the same feeds.
export const SOURCES = [
  {
    id: 'thaiwater_wl',
    kind: 'pipeline',
    stored: true,
    name_th: 'ระดับน้ำ สสน. (ThaiWater)',
    name_en: 'HII ThaiWater — water level',
    agency_th: 'สถาบันสารสนเทศทรัพยากรน้ำ (สสน.)',
    agency_en: 'Hydro-Informatics Institute (HII)',
    cadence_th: 'ทุก 10 นาที',
    cadence_en: 'every 10 minutes',
    url: 'https://www.thaiwater.net/',
    api: '/api/snapshot · /api/series?source=thaiwater_wl',
    metrics: ['situation_level', 'wl_msl', 'storage_pct'],
    note_th: 'สถานีโทรมาตร ~776 แห่ง · ระดับสถานการณ์ 1–5',
    note_en: '~776 telemetry stations · HII situation levels 1–5',
  },
  {
    id: 'thaiwater_rain',
    kind: 'pipeline',
    stored: true,
    name_th: 'ฝนสะสม 24 ชม. (ThaiWater)',
    name_en: 'Multi-agency rain gauges (ThaiWater)',
    agency_th: 'หลายหน่วยงานผ่าน สสน.',
    agency_en: 'Multi-agency via HII',
    cadence_th: 'ทุก 10 นาที',
    cadence_en: 'every 10 minutes',
    url: 'https://www.thaiwater.net/',
    api: '/api/snapshot · /api/series?source=thaiwater_rain',
    metrics: ['rain_24h', 'rain_1h'],
    note_th: 'สถานีฝน ~4,200 แห่ง',
    note_en: '~4,200 rain gauges nationwide',
  },
  {
    id: 'thaiwater_dam',
    kind: 'pipeline',
    stored: true,
    name_th: 'เขื่อนขนาดใหญ่',
    name_en: 'Major dams',
    agency_th: 'สสน. / กฟผ. / กรมชลประทาน',
    agency_en: 'HII · EGAT · RID',
    cadence_th: 'ทุก 1 ชม.',
    cadence_en: 'hourly',
    url: 'https://www.thaiwater.net/',
    api: '/api/snapshot · /api/series?source=thaiwater_dam',
    metrics: ['dam_storage_pct', 'dam_storage_mcm', 'dam_inflow_mcm', 'dam_released_mcm'],
    note_th: 'เขื่อนหลัก ~35–50 แห่ง',
    note_en: '~35–50 major dams',
  },
  {
    id: 'rid_reservoir',
    kind: 'pipeline',
    stored: true,
    name_th: 'อ่างเก็บน้ำขนาดกลาง กรมชลฯ',
    name_en: 'RID medium reservoirs',
    agency_th: 'กรมชลประทาน',
    agency_en: 'Royal Irrigation Department (RID)',
    cadence_th: 'ทุก 6 ชม.',
    cadence_en: 'every 6 hours',
    url: 'https://app.rid.go.th/reservoir/reservoir',
    api: '/api/snapshot · /api/series?source=rid_reservoir',
    metrics: ['rsv_storage_pct', 'rsv_volume_mcm'],
    note_th: 'อ่างขนาดกลาง ~461 แห่ง',
    note_en: '~461 medium reservoirs',
  },
  {
    id: 'air4thai',
    kind: 'pipeline',
    stored: true,
    name_th: 'คุณภาพอากาศ Air4Thai',
    name_en: 'Air4Thai AQI / PM2.5',
    agency_th: 'กรมควบคุมมลพิษ (คพ.)',
    agency_en: 'Pollution Control Department (PCD)',
    cadence_th: 'ทุก 1 ชม.',
    cadence_en: 'hourly',
    url: 'https://air4thai.pcd.go.th/',
    api: '/api/snapshot · /api/series?source=air4thai',
    metrics: ['aqi', 'pm25'],
    note_th: 'สถานี ~174 แห่ง — บริบทสุขภาพช่วงน้ำท่วม',
    note_en: '~174 stations — health context during floods',
  },
  {
    id: 'openmeteo',
    kind: 'pipeline',
    stored: true,
    name_th: 'พยากรณ์ฝน Open-Meteo',
    name_en: 'Open-Meteo rain forecast',
    agency_th: 'Open-Meteo (จุดกึ่งกลางจังหวัดจากสถานีจริง)',
    agency_en: 'Open-Meteo (province centroids from real stations)',
    cadence_th: 'ทุก 3 ชม.',
    cadence_en: 'every 3 hours',
    url: 'https://open-meteo.com/',
    api: '/api/snapshot · /api/series?source=openmeteo',
    metrics: ['precip_fc_d0', 'precip_fc_d1', 'precip_fc_d2', 'precip_fc_48h'],
    note_th: 'พยากรณ์ 48 ชม. ต่อจังหวัด — ใช้ในดัชนีเฝ้าระวัง 20%',
    note_en: '48h province forecast — 20% of watch score',
  },
  {
    id: 'glofas',
    kind: 'pipeline',
    stored: true,
    name_th: 'อัตราการไหลแม่น้ำ GloFAS',
    name_en: 'GloFAS river discharge (Copernicus)',
    agency_th: 'Copernicus EMS · ผ่าน Open-Meteo Flood API',
    agency_en: 'Copernicus EMS via Open-Meteo Flood API',
    cadence_th: 'ทุก 3 ชม.',
    cadence_en: 'every 3 hours',
    url: 'https://www.globalfloods.eu/',
    api: '/api/rivers · /api/series?source=glofas',
    metrics: ['discharge', 'discharge_fc_peak', 'discharge_fc_peak_day'],
    note_th: 'เครือข่ายน้ำเชื่อมโยง ~15 จุด · m³/s',
    note_en: '~15 connected reaches · m³/s cascade engine',
  },
  {
    id: 'enso',
    kind: 'pipeline',
    stored: true,
    name_th: 'ดัชนี ONI / ENSO',
    name_en: 'ENSO / ONI ocean state (NOAA)',
    agency_th: 'NOAA Climate Prediction Center',
    agency_en: 'NOAA Climate Prediction Center',
    cadence_th: 'ทุก 12 ชม.',
    cadence_en: 'every 12 hours',
    url: 'https://www.cpc.ncep.noaa.gov/products/analysis_monitoring/ensostuff/ONI_v5.php',
    api: '/api/enso',
    metrics: ['oni_anom'],
    note_th: 'ตัวปรับฤดูกาล ไม่ใช่ตัวพยากรณ์',
    note_en: 'Seasonal modulator, not a forecast',
  },
  {
    id: 'news',
    kind: 'pipeline',
    stored: true,
    name_th: 'ข่าวน้ำท่วม RSS',
    name_en: 'Flood news RSS',
    agency_th: 'Google News TH · ข่าวสด',
    agency_en: 'Google News TH · Khaosod',
    cadence_th: 'ทุก 30 นาที',
    cadence_en: 'every 30 minutes',
    url: 'https://news.google.com/',
    api: '/api/news',
    metrics: [],
    note_th: 'กรองคำค้น น้ำท่วม / อุทกภัย',
    note_en: 'Keyword-filtered flood headlines',
  },
  {
    id: 'imerg',
    kind: 'pipeline',
    stored: true,
    name_th: 'ฝนดาวเทียม GPM IMERG',
    name_en: 'GPM IMERG satellite rain (NASA)',
    agency_th: 'NASA GES DISC · GPM Mission',
    agency_en: 'NASA GES DISC · Global Precipitation Measurement',
    cadence_th: 'ทุก 30 นาที (IMERG Early ~4h latency)',
    cadence_en: 'every 30 minutes (IMERG Early ~4h latency)',
    url: 'https://gpm.nasa.gov/data',
    api: '/api/snapshot (sat_rain) · /api/series?source=imerg',
    metrics: ['sat_rain_mmh'],
    note_th: 'ฝนจากดาวเทียม 0.1° — ตรวจสอบจุดที่ไม่มีสถานี · ต้องใช้ NASA Earthdata token',
    note_en: '0.1° satellite rain — cross-checks ungauged cells · requires NASA Earthdata token',
  },
  // ── Remote sensing (map layers — not stored in SQLite) ─────────────────────
  {
    id: 'gsmap',
    kind: 'satellite',
    stored: false,
    name_th: 'GSMaP — ฝนจากดาวเทียม (JAXA/GPM)',
    name_en: 'GSMaP satellite precipitation (JAXA/GPM)',
    agency_th: 'JAXA · Global Precipitation Measurement',
    agency_en: 'JAXA Earth Observation Research Center · GPM',
    cadence_th: 'รายชั่วโมง · 0.1°',
    cadence_en: 'hourly · 0.1° global',
    url: 'https://earth.jaxa.jp/en/data/index.html',
    api: 'https://data.earth.jaxa.jp/ (JAXA Earth API · COG/WMTS)',
    metrics: ['precipitation_rate'],
    note_th: 'HII ใช้ GSMaP ในระบบเฝ้าระวังฝน · แผนที่แสดงผ่าน GPM IMERG (NASA GIBS)',
    note_en: 'HII uses GSMaP operationally; map shows GPM IMERG via NASA GIBS tiles',
  },
  {
    id: 'himawari',
    kind: 'satellite',
    stored: false,
    name_th: 'Himawari-9 — ภาพเมฆ (JAXA/JMA)',
    name_en: 'Himawari-9 cloud imagery (JAXA/JMA)',
    agency_th: 'JAXA P-Tree · กรมอุตุนิยมวิทยา',
    agency_en: 'JAXA Himawari Monitor (P-Tree) · JMA',
    cadence_th: 'ทุก 10 นาที (full disk)',
    cadence_en: '10-minute full disk',
    url: 'https://www.eorc.jaxa.jp/ptree/',
    api: 'NASA GIBS WMTS · Band 13 IR + true colour',
    metrics: [],
    note_th: 'ติดตามพายุฝนหนาแน่น · แผนที่ใช้ GIBS EPSG:3857',
    note_en: 'Dense cloud / storm tracking · GIBS Web Mercator tiles',
  },
  {
    id: 'modis',
    kind: 'satellite',
    stored: false,
    name_th: 'MODIS Terra — ภาพจริง (NASA)',
    name_en: 'MODIS Terra true colour (NASA)',
    agency_th: 'NASA GIBS',
    agency_en: 'NASA Global Imagery Browse Services',
    cadence_th: 'รายวัน',
    cadence_en: 'daily',
    url: 'https://gibs.earthdata.nasa.gov/',
    api: 'GIBS WMTS MODIS_Terra_CorrectedReflectance_TrueColor',
    metrics: [],
    note_th: 'ภาพพื้นผิวเมื่อเมฆน้อย · max zoom 9',
    note_en: 'Surface view on clear days · native zoom 9',
  },
  {
    id: 'rainviewer',
    kind: 'satellite',
    stored: false,
    name_th: 'เรดาร์ฝน RainViewer',
    name_en: 'RainViewer weather radar mosaic',
    agency_th: 'RainViewer (รวมเรดารนภาค)',
    agency_en: 'RainViewer (regional radar composite)',
    cadence_th: 'ทุก ~10 นาที · แอนิเมชัน',
    cadence_en: '~10 min · animated',
    url: 'https://www.rainviewer.com/',
    api: 'https://api.rainviewer.com/public/weather-maps.json',
    metrics: [],
    note_th: 'เรดารนฝนภาค · ไม่เก็บลงฐานข้อมูล',
    note_en: 'Regional radar tiles · not persisted',
  },
  {
    id: 'rivers_geo',
    kind: 'reference',
    stored: false,
    name_th: 'เครือข่ายแม่น้ำไทย (GISTDA)',
    name_en: 'Thai river network (GISTDA)',
    agency_th: 'สำนักงานพัฒนาเทคโนโลยีอวกาศและภูมิสารสนเทศ (GISTDA)',
    agency_en: 'GISTDA',
    cadence_th: 'คงที่',
    cadence_en: 'static GeoJSON',
    url: 'https://www.gistda.or.th/',
    api: '/geo/thai-rivers.geojson',
    metrics: [],
    note_th: 'เส้นทางน้ำจริงบนแผนที่',
    note_en: 'Real channel geometry on the map',
  },
]

export const EXPORT_INFO = {
  method_th: 'ข้อมูลดิบ 90 วัน · รวมรายชั่วโมงถาวรหลังจากนั้น · ส่งออกรายวันต่อสถานี/ตัวชี้วัด',
  method_en: 'Raw readings kept 90 days · permanent hourly rollups thereafter · daily export per station/metric',
  formats: ['json', 'csv'],
  endpoints: {
    catalog: 'GET /api/export/days',
    daily: 'GET /api/export/daily?date=YYYY-MM-DD&format=json|csv',
    full: 'GET /api/export/full (CSV · all permanent hourly aggregates)',
    stations: 'GET /api/stations?q=…',
    series: 'GET /api/series?source&station&metric&hours',
  },
}
