// Canonical catalog of every data source AirDash uses — polled pipelines,
// map-only remote-sensing layers (JAXA / NASA GIBS / RainViewer), reference
// portals, and the compiled exports we serve from SQLite. Exposed at
// GET /api/sources for researchers and integrators who want the same feeds.
export const SOURCES = [
  {
    id: 'air4thai',
    kind: 'pipeline',
    stored: true,
    name_th: 'คุณภาพอากาศ Air4Thai',
    name_en: 'Air4Thai AQI / PM2.5 (PCD)',
    agency_th: 'กรมควบคุมมลพิษ (คพ.)',
    agency_en: 'Pollution Control Department (PCD)',
    cadence_th: 'ทุก 1 ชม.',
    cadence_en: 'hourly',
    url: 'https://air4thai.pcd.go.th/',
    api: '/api/snapshot · /api/series?source=air4thai',
    metrics: ['pm25', 'pm10', 'o3', 'co', 'no2', 'so2', 'aqi'],
    note_th: 'สถานีภาคพื้น ~200 แห่ง — แหล่งข้อมูลหลัก · PM µg/m³ · O3/NO2/SO2 ppb · CO ppm',
    note_en: '~200 ground stations — PRIMARY source · PM µg/m³ · O3/NO2/SO2 ppb · CO ppm',
  },
  {
    id: 'openmeteo',
    kind: 'pipeline',
    stored: true,
    name_th: 'พยากรณ์อากาศ Open-Meteo (ฝน/ลม)',
    name_en: 'Open-Meteo weather forecast (rain/wind)',
    agency_th: 'Open-Meteo (จุดกึ่งกลาง 77 จังหวัด)',
    agency_en: 'Open-Meteo (77 province centroids)',
    cadence_th: 'ทุก 3 ชม.',
    cadence_en: 'every 3 hours',
    url: 'https://open-meteo.com/',
    api: '/api/snapshot · /api/series?source=openmeteo',
    metrics: ['precip_fc_d0', 'precip_fc_d1', 'precip_fc_d2', 'precip_fc_48h',
              'precip_prob_d0', 'precip_prob_d1', 'precip_prob_d2',
              'precip_prob_24h', 'precip_prob_48h', 'wind_fc_kmh', 'wind_fc_d1'],
    note_th: 'โอกาสฝน + ปริมาณฝน + ลม ต่อจังหวัด — ป้อนเครื่องยนต์ฝนล้างฝุ่นและดัชนีการระบายอากาศ',
    note_en: 'Rain probability + amount + wind per province — feeds the washout engine and ventilation score',
  },
  {
    id: 'openmeteo_aq',
    kind: 'pipeline',
    stored: true,
    name_th: 'พยากรณ์ฝุ่น CAMS (Open-Meteo Air Quality)',
    name_en: 'CAMS air-quality forecast (Open-Meteo AQ API)',
    agency_th: 'Copernicus CAMS ผ่าน Open-Meteo',
    agency_en: 'Copernicus CAMS via Open-Meteo',
    cadence_th: 'ทุก 3 ชม. (โมเดลอัปเดตทุก 12 ชม.)',
    cadence_en: 'every 3 hours (12-hourly model cycles upstream)',
    url: 'https://open-meteo.com/en/docs/air-quality-api',
    api: '/api/snapshot · /api/series?source=openmeteo_aq',
    metrics: ['pm25_fc_24h', 'pm25_fc_48h', 'pm25_fc_72h', 'pm10_fc_24h', 'dust_fc_24h'],
    note_th: 'พยากรณ์ PM2.5/PM10/ฝุ่นทะเลทราย 24–72 ชม. ต่อจังหวัด — ใช้ในดัชนีเฝ้าระวัง 20%',
    note_en: '24–72h PM2.5/PM10/dust forecast per province — 20% of the watch score',
  },
  {
    id: 'thaiwater_rain',
    kind: 'pipeline',
    stored: true,
    name_th: 'ฝนสะสม 24 ชม. (ThaiWater)',
    name_en: 'Multi-agency rain gauges (ThaiWater)',
    agency_th: 'หลายหน่วยงานผ่าน สสน.',
    agency_en: 'Multi-agency via HII',
    cadence_th: 'ทุก 10 นาที',
    cadence_en: 'every 10 minutes',
    url: 'https://www.thaiwater.net/',
    api: '/api/snapshot · /api/series?source=thaiwater_rain',
    metrics: ['rain_24h', 'rain_1h'],
    note_th: 'สถานีฝน ~4,200 แห่ง — ยืนยันว่าฝนล้างฝุ่นเกิดขึ้นจริง',
    note_en: '~4,200 rain gauges — observed verification that washout actually happened',
  },
  {
    id: 'imerg',
    kind: 'pipeline',
    stored: true,
    name_th: 'ฝนดาวเทียม GPM IMERG',
    name_en: 'GPM IMERG satellite rain (NASA)',
    agency_th: 'NASA GES DISC · GPM Mission',
    agency_en: 'NASA GES DISC · Global Precipitation Measurement',
    cadence_th: 'ทุก 30 นาที (IMERG Early ~4h latency)',
    cadence_en: 'every 30 minutes (IMERG Early ~4h latency)',
    url: 'https://gpm.nasa.gov/data',
    api: '/api/snapshot (sat_rain) · /api/series?source=imerg',
    metrics: ['sat_rain_mmh'],
    note_th: 'ฝนจากดาวเทียม 0.1° — ตรวจสอบพื้นที่ที่ไม่มีสถานีฝน · ต้องใช้ NASA Earthdata token',
    note_en: '0.1° satellite rain — cross-checks ungauged cells · requires NASA Earthdata token',
  },
  {
    id: 'enso',
    kind: 'pipeline',
    stored: true,
    name_th: 'ดัชนี ONI / ENSO',
    name_en: 'ENSO / ONI ocean state (NOAA)',
    agency_th: 'NOAA Climate Prediction Center',
    agency_en: 'NOAA Climate Prediction Center',
    cadence_th: 'ทุก 12 ชม.',
    cadence_en: 'every 12 hours',
    url: 'https://www.cpc.ncep.noaa.gov/products/analysis_monitoring/ensostuff/ONI_v5.php',
    api: '/api/enso',
    metrics: ['oni_anom'],
    note_th: 'เอลนีโญ = แล้ง = ฤดูฝุ่นรุนแรงขึ้น — ตัวปรับฤดูกาล ไม่ใช่ตัวพยากรณ์',
    note_en: 'El Niño = drier = worse dust season — seasonal modulator, not a forecast',
  },
  {
    id: 'news',
    kind: 'pipeline',
    stored: true,
    name_th: 'ข่าวฝุ่น PM2.5 RSS',
    name_en: 'Dust / PM2.5 news RSS',
    agency_th: 'Google News TH · ข่าวสด',
    agency_en: 'Google News TH · Khaosod',
    cadence_th: 'ทุก 30 นาที',
    cadence_en: 'every 30 minutes',
    url: 'https://news.google.com/',
    api: '/api/news',
    metrics: [],
    note_th: 'กรองคำค้น ฝุ่น / PM2.5 / หมอกควัน',
    note_en: 'Keyword-filtered dust / PM2.5 / haze headlines',
  },
  // ── Remote sensing (map layers — not stored in SQLite) ─────────────────────
  {
    id: 'gsmap',
    kind: 'satellite',
    stored: false,
    name_th: 'GSMaP — ฝนจากดาวเทียม (JAXA/GPM)',
    name_en: 'GSMaP satellite precipitation (JAXA/GPM)',
    agency_th: 'JAXA · Global Precipitation Measurement',
    agency_en: 'JAXA Earth Observation Research Center · GPM',
    cadence_th: 'รายชั่วโมง · 0.1°',
    cadence_en: 'hourly · 0.1° global',
    url: 'https://earth.jaxa.jp/en/data/index.html',
    api: 'https://data.earth.jaxa.jp/ (JAXA Earth API · COG/WMTS)',
    metrics: ['precipitation_rate'],
    note_th: 'ฝนดาวเทียมสำหรับติดตามโอกาสฝนล้างฝุ่น · แผนที่แสดงผ่าน GPM IMERG (NASA GIBS)',
    note_en: 'Satellite rain for washout tracking; map shows GPM IMERG via NASA GIBS tiles',
  },
  {
    id: 'himawari',
    kind: 'satellite',
    stored: false,
    name_th: 'Himawari-9 — ภาพเมฆ/หมอกควัน (JAXA/JMA)',
    name_en: 'Himawari-9 cloud & haze imagery (JAXA/JMA)',
    agency_th: 'JAXA P-Tree · กรมอุตุนิยมวิทยา',
    agency_en: 'JAXA Himawari Monitor (P-Tree) · JMA',
    cadence_th: 'ทุก 10 นาที (full disk)',
    cadence_en: '10-minute full disk',
    url: 'https://www.eorc.jaxa.jp/ptree/',
    api: 'NASA GIBS WMTS · Band 13 IR + true colour',
    metrics: [],
    note_th: 'ติดตามเมฆฝนและกลุ่มหมอกควันขนาดใหญ่ · แผนที่ใช้ GIBS EPSG:3857',
    note_en: 'Rain-cloud + regional haze-plume tracking · GIBS Web Mercator tiles',
  },
  {
    id: 'modis',
    kind: 'satellite',
    stored: false,
    name_th: 'MODIS Terra — ภาพจริง (NASA)',
    name_en: 'MODIS Terra true colour (NASA)',
    agency_th: 'NASA GIBS',
    agency_en: 'NASA Global Imagery Browse Services',
    cadence_th: 'รายวัน',
    cadence_en: 'daily',
    url: 'https://gibs.earthdata.nasa.gov/',
    api: 'GIBS WMTS MODIS_Terra_CorrectedReflectance_TrueColor',
    metrics: [],
    note_th: 'เห็นกลุ่มควันไฟป่า/การเผาในภาพจริงเมื่อเมฆน้อย · max zoom 9',
    note_en: 'Smoke plumes from fires/burning visible on clear days · native zoom 9',
  },
  {
    id: 'aod',
    kind: 'satellite',
    stored: false,
    name_th: 'ความหนาแน่นละอองลอย AOD (MODIS Terra+Aqua)',
    name_en: 'Aerosol Optical Depth (MODIS Terra+Aqua)',
    agency_th: 'NASA GIBS · MODIS combined value-added',
    agency_en: 'NASA Global Imagery Browse Services · MODIS combined',
    cadence_th: 'รายวัน (ประมวลผลข้ามคืน · แสดงของเมื่อวาน)',
    cadence_en: 'daily (processed overnight · shows yesterday)',
    url: 'https://gibs.earthdata.nasa.gov/',
    api: 'GIBS WMTS MODIS_Combined_Value_Added_AOD',
    metrics: [],
    note_th: 'ปริมาณฝุ่นละอองทั้งคอลัมน์อากาศจากดาวเทียม — เห็นแนวหมอกควันจากไฟป่า/การเผาที่ลอยเข้ามาก่อนสถานีภาคพื้นดินปลายลมจะจับค่า PM2.5 ได้ · ชั้นหลักของฤดูเผา',
    note_en: 'Column aerosol loading from space — a plume of smoke advecting in from upwind fires shows here before the downwind ground stations register the PM2.5 spike · the burning-season layer',
  },
  {
    id: 'nightlights',
    kind: 'satellite',
    stored: false,
    name_th: 'แสงไฟกลางคืน VIIRS Day/Night Band (NASA)',
    name_en: 'VIIRS Day/Night Band night lights (NASA)',
    agency_th: 'NASA GIBS · Suomi-NPP VIIRS',
    agency_en: 'NASA Global Imagery Browse Services · Suomi-NPP VIIRS',
    cadence_th: 'รายคืน (ประมวลผลช้า ~2 วัน)',
    cadence_en: 'nightly (processed ~2 days behind)',
    url: 'https://gibs.earthdata.nasa.gov/',
    api: 'GIBS WMTS VIIRS_SNPP_DayNightBand_At_Sensor_Radiance',
    metrics: [],
    note_th: 'ไฟเผาไร่มักจุดตอนหัวค่ำเพราะอากาศเย็นและคนเห็นน้อย — แถบ Day/Night Band จับแสงไฟนั้นได้โดยตรง จุดสว่างนอกเขตเมืองจึงเป็นเบาะแสของการเผากลางคืน และในคืนที่หมอกควันหนา แสงเมืองจะฟุ้งกระจายผิดปกติ · ข้อควรระวัง: แสงจันทร์ก็ทำให้ภาพสว่างขึ้นเช่นกัน',
    note_en: 'Field burning is often lit in the evening (cooler, less visible), and the Day/Night Band sees that light directly — bright points outside towns are a clue to night burning. On thick-haze nights city light scatters and blooms. Caveat: moonlight also brightens the scene, so compare across the lunar cycle.',
  },
  {
    id: 'rainviewer',
    kind: 'satellite',
    stored: false,
    name_th: 'เรดาร์ฝน RainViewer',
    name_en: 'RainViewer weather radar mosaic',
    agency_th: 'RainViewer (รวมเรดารนภาค)',
    agency_en: 'RainViewer (regional radar composite)',
    cadence_th: 'ทุก ~10 นาที · แอนิเมชัน',
    cadence_en: '~10 min · animated',
    url: 'https://www.rainviewer.com/',
    api: 'https://api.rainviewer.com/public/weather-maps.json',
    metrics: [],
    note_th: 'เรดาร์ฝนเรียลไทม์ — ฝนที่กำลังตก = ฝุ่นกำลังถูกชะล้าง · ไม่เก็บลงฐานข้อมูล',
    note_en: 'Live rain radar — rain falling now means washout in progress · not persisted',
  },
  // ── Reference portals & alternate access (not polled) ─────────────────────
  {
    id: 'servir_aq',
    kind: 'reference',
    stored: false,
    name_th: 'SERVIR-Mekong Air Quality Explorer',
    name_en: 'SERVIR-Mekong Air Quality Explorer',
    agency_th: 'ADPC · NASA · USAID',
    agency_en: 'ADPC · NASA · USAID',
    cadence_th: 'รายวัน (ดาวเทียม + โมเดล)',
    cadence_en: 'daily (satellite + model)',
    url: 'https://aqatmekong-servir.adpc.net/',
    api: 'https://aqatmekong-servir.adpc.net/ (web portal)',
    metrics: [],
    note_th: 'แผนที่ฝุ่น/ไฟป่าระดับลุ่มน้ำโขงจากดาวเทียม — ใช้เทียบภาพรวมภูมิภาค',
    note_en: 'Mekong-region satellite AQ/fire portal — regional cross-reference',
  },
  {
    id: 'openaq',
    kind: 'reference',
    stored: false,
    name_th: 'OpenAQ — API คุณภาพอากาศเปิด',
    name_en: 'OpenAQ open air-quality API',
    agency_th: 'OpenAQ (รวมข้อมูลทางการทั่วโลก)',
    agency_en: 'OpenAQ (global aggregator of official monitors)',
    cadence_th: 'รายชั่วโมง',
    cadence_en: 'hourly',
    url: 'https://openaq.org/',
    api: 'https://docs.openaq.org/',
    metrics: [],
    note_th: 'ช่องทางสำรองเข้าถึงข้อมูลสถานี คพ. ผ่าน API มาตรฐานเดียวทั่วโลก',
    note_en: 'Alternate access to PCD station data through one standard global API',
  },
  {
    id: 'waqi',
    kind: 'reference',
    stored: false,
    name_th: 'WAQI — World Air Quality Index',
    name_en: 'WAQI — World Air Quality Index',
    agency_th: 'World Air Quality Index Project',
    agency_en: 'World Air Quality Index Project',
    cadence_th: 'รายชั่วโมง',
    cadence_en: 'hourly',
    url: 'https://aqicn.org/',
    api: 'https://aqicn.org/data-platform/api/',
    metrics: [],
    note_th: 'ช่องทางสำรอง AQI รายสถานีทั่วโลก (รวมสถานีไทย) — ใช้ตรวจทานค่า',
    note_en: 'Alternate per-station AQI worldwide (incl. Thai stations) — cross-validation',
  },
]

export const EXPORT_INFO = {
  method_th: 'ข้อมูลดิบ 90 วัน · รวมรายชั่วโมงถาวรหลังจากนั้น · ส่งออกรายวันต่อสถานี/ตัวชี้วัด (PM2.5 · PM10 · O3 · NO2 · SO2 · CO · AQI · ฝน · พยากรณ์)',
  method_en: 'Raw readings kept 90 days · permanent hourly rollups thereafter · daily export per station/metric (PM2.5 · PM10 · O3 · NO2 · SO2 · CO · AQI · rain · forecasts)',
  formats: ['json', 'csv'],
  endpoints: {
    catalog: 'GET /api/export/days',
    daily: 'GET /api/export/daily?date=YYYY-MM-DD&format=json|csv',
    full: 'GET /api/export/full (CSV · all permanent hourly aggregates)',
    stations: 'GET /api/stations?q=…',
    series: 'GET /api/series?source&station&metric&hours',
  },
}
